# Generated by Django 3.2.5 on 2021-08-31 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AMCE', '0010_remove_profile_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Votar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMCE.clases')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.AddField(
            model_name='anadir',
            name='codigo_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AMCE.clases'),
        ),
        migrations.AddField(
            model_name='anadir',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
